# Generated by Django 3.0.5 on 2020-09-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministros', '0002_pastorpage_iglesia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastorpage',
            name='pastor_wife',
            field=models.CharField(blank=True, help_text='Nombre de la esposa del pastor', max_length=250, null=True),
        ),
    ]
