# Generated by Django 5.2.1 on 2025-08-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='experiencia',
            field=models.TextField(blank=True, help_text='Experiencia ministerial', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fecha_ordenacion',
            field=models.DateField(blank=True, help_text='Fecha de ordenación ministerial', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='iglesia_principal',
            field=models.CharField(blank=True, help_text='Nombre de la iglesia principal', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='titulo_academico',
            field=models.CharField(blank=True, help_text='Título académico/teológico', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('pastor_elim', 'Soy pastor Elim'), ('pastor_otro', 'Soy pastor - otro ministerio o independiente')], default='pastor_elim', max_length=20),
        ),
    ]
