# Generated by Django 5.2.1 on 2025-12-28 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0007_cityindexpage_countryindexpage_iglesiapage'),
        ('pastores', '0002_userprofile_experiencia_userprofile_fecha_ordenacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='iglesia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pastores', to='iglesias.iglesiapage', verbose_name='Iglesia Asignada'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='iglesia_principal',
            field=models.CharField(blank=True, help_text='Nombre de la iglesia principal (Legacy)', max_length=255, null=True),
        ),
    ]
