# Generated by Django 5.2.1 on 2025-12-28 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastores', '0003_userprofile_iglesia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pastores_a_cargo', to='pastores.userprofile', verbose_name='Supervisor (Apóstol/Pastor de Pastores)'),
        ),
    ]
