# Generated by Django 5.2.9 on 2025-12-28 01:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastores', '0004_userprofile_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='biography',
            field=wagtail.fields.RichTextField(blank=True, help_text='Historia del pastor, sus inicios y testimonio.', null=True, verbose_name='Biografía / Historia'),
        ),
    ]
