# Generated by Django 5.2.9 on 2025-12-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastores', '0005_userprofile_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_apostle',
            field=models.BooleanField(default=False, verbose_name='¿Es Apóstol?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_superpastor',
            field=models.BooleanField(default=False, verbose_name='¿Es Pastor de Pastores (Superpastor)?'),
        ),
    ]
