# Generated by Django 5.2.1 on 2025-12-28 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0007_cityindexpage_countryindexpage_iglesiapage'),
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='iglesia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros', to='iglesias.iglesiapage', verbose_name='Iglesia Afiliada'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='is_approved_member',
            field=models.BooleanField(default=False, help_text='Indica si el pastor ha aprobado a este miembro.', verbose_name='Miembro Aprobado'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='iglesia_afiliada',
            field=models.CharField(blank=True, help_text='Nombre de la iglesia a la que pertenece (Legacy)', max_length=255, null=True),
        ),
    ]
