# Generated by Django 5.2.1 on 2025-12-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_memberprofile_iglesia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='role',
            field=models.CharField(choices=[('miembro', 'Soy miembro de una iglesia (Elim u otra iglesia)'), ('ayuda', 'Soy ayuda / supermiembro'), ('visitante', 'Solo soy visitante')], default='miembro', max_length=20),
        ),
    ]
