# Generated by Django 3.0.5 on 2020-08-31 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('costo_despacho_con_recojo', models.IntegerField(default=15)),
                ('costo_despacho_sin_recojo', models.IntegerField(default=15)),
                ('dias_despacho', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('dni', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('shipping_address1', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('shipping_department', models.CharField(max_length=100)),
                ('shipping_province', models.CharField(max_length=100)),
                ('shipping_district', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='profile_pics/default_profile_pic_white.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
