# Generated by Django 3.0.5 on 2020-09-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reference',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
