# Generated by Django 3.0.5 on 2020-09-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile_pics/default_profile_pic.png', upload_to='profile_pics'),
        ),
    ]
