# Generated by Django 5.2.1 on 2025-08-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_update_pastor_to_pastor_elim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('pastor_elim', 'Soy pastor Elim'), ('pastor_otro', 'Soy pastor - otro ministerio o independiente'), ('miembro', 'Soy miembro de una iglesia (Elim u otra iglesia)'), ('visitante', 'Solo soy visitante')], default='visitante', max_length=20),
        ),
    ]
