# Generated by Django 5.2.1 on 2025-08-26 16:51

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_add_country_to_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
