# Generated by Django 5.2.1 on 2025-08-27 23:15

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_add_phone_to_userprofile'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('pastor_elim', 'Soy pastor Elim'), ('pastor_otro', 'Soy pastor - otro ministerio o independiente'), ('miembro', 'Soy miembro de una iglesia (Elim u otra iglesia)'), ('visitante', 'Solo soy visitante')], default='miembro', max_length=20),
        ),
        migrations.CreateModel(
            name='ChurchPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('church_name', models.CharField(help_text='Nombre de la iglesia', max_length=200)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Descripción de la iglesia')),
                ('address', models.TextField(blank=True, help_text='Dirección completa')),
                ('contact_phone', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20)),
                ('facebook_url', models.URLField(blank=True, help_text='URL de Facebook')),
                ('instagram_url', models.URLField(blank=True, help_text='URL de Instagram')),
                ('tiktok_url', models.URLField(blank=True, help_text='URL de TikTok')),
                ('twitter_url', models.URLField(blank=True, help_text='URL de X (Twitter)')),
                ('church_image', models.ForeignKey(blank=True, help_text='Foto de la iglesia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
