# Generated by Django 5.2.1 on 2025-08-28 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_add_foto_to_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
