# Generated by Django 5.2.1 on 2025-11-10 02:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([], blank=True, block_lookup={}, default=[], null=True),
        ),
    ]
