# Generated by Django 5.2.9 on 2025-12-28 04:30

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_homepage_content'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoWeArePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction_title', models.CharField(default='Quiénes Somos', max_length=255)),
                ('introduction_text', wagtail.fields.RichTextField(blank=True, verbose_name='Texto de Introducción')),
                ('apostle_title', models.CharField(default='Apóstol Jorge Fuentes', max_length=255)),
                ('apostle_subtitle', models.CharField(default='Fundador y Cobertura Espiritual', max_length=255)),
                ('apostle_bio', wagtail.fields.RichTextField(blank=True, verbose_name='Biografía del Apóstol')),
                ('apostle_quote', models.TextField(blank=True, verbose_name='Cita / Pensamiento')),
                ('hierarchy_title', models.CharField(default='Nuestra Estructura Ministerial', max_length=255)),
                ('hierarchy_description', models.TextField(blank=True, verbose_name='Descripción de la Jerarquía')),
                ('apostle_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen del Apóstol')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
