# Generated by Django 3.0.5 on 2020-05-28 04:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Ingrese un título', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Añade texto adicional', required=True))], classname='text_and_title'))], blank=True, null=True),
        ),
    ]
