# Generated by Django 5.2.1 on 2025-08-26 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Iglesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('lugar', models.CharField(blank=True, max_length=255)),
                ('dias_horarios', models.CharField(blank=True, help_text='Ej: Domingos 10:00, Miércoles 19:00', max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iglesias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Iglesia',
                'verbose_name_plural': 'Iglesias',
            },
        ),
    ]
