# Generated by Django 5.2.1 on 2025-08-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iglesia',
            name='country',
            field=models.CharField(blank=True, help_text='País donde está ubicada la iglesia', max_length=100),
        ),
    ]
