# Generated by Django 3.0.5 on 2020-09-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0002_auto_20200914_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='iglesiapage',
            name='formatted_address',
            field=models.CharField(default='Lima', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iglesiapage',
            name='latlng_address',
            field=models.CharField(default='Lima', max_length=255),
            preserve_default=False,
        ),
    ]
