# Generated by Django 5.2.1 on 2025-08-26 16:29

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0002_iglesia_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iglesia',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='País donde está ubicada la iglesia', max_length=2, null=True),
        ),
    ]
