# Generated by Django 5.2.1 on 2025-08-28 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0003_alter_iglesia_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iglesia',
            old_name='lugar',
            new_name='address',
        ),
    ]
