# Generated by Django 5.2.1 on 2025-08-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0004_rename_lugar_to_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iglesia',
            name='dias_horarios',
        ),
        migrations.AddField(
            model_name='iglesia',
            name='culto_general',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='iglesia',
            name='culto_oracion',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='iglesia',
            name='estudio_biblico',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=10, null=True),
        ),
    ]
