# Generated by Django 5.2.1 on 2025-08-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0005_replace_horarios_with_specific_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='iglesia',
            name='culto_general_dia',
            field=models.CharField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20, null=True, verbose_name='Día - Culto General'),
        ),
        migrations.AddField(
            model_name='iglesia',
            name='culto_general_hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora - Culto General'),
        ),
        migrations.AddField(
            model_name='iglesia',
            name='culto_oracion_dia',
            field=models.CharField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20, null=True, verbose_name='Día - Culto de Oración'),
        ),
        migrations.AddField(
            model_name='iglesia',
            name='culto_oracion_hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora - Culto de Oración'),
        ),
        migrations.AddField(
            model_name='iglesia',
            name='estudio_biblico_dia',
            field=models.CharField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20, null=True, verbose_name='Día - Estudio Bíblico'),
        ),
        migrations.AddField(
            model_name='iglesia',
            name='estudio_biblico_hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora - Estudio Bíblico'),
        ),
        migrations.AlterField(
            model_name='iglesia',
            name='culto_general',
            field=models.CharField(blank=True, choices=[('a. m.', 'a. m.'), ('p. m.', 'p. m.')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='iglesia',
            name='culto_oracion',
            field=models.CharField(blank=True, choices=[('a. m.', 'a. m.'), ('p. m.', 'p. m.')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='iglesia',
            name='estudio_biblico',
            field=models.CharField(blank=True, choices=[('a. m.', 'a. m.'), ('p. m.', 'p. m.')], max_length=10, null=True),
        ),
    ]
