# Generated by Django 5.2.1 on 2025-12-28 00:01

import django.db.models.deletion
import django_countries.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0006_add_detailed_schedule_fields'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CountryIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='País')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='IglesiaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Sobre nosotros')),
                ('worship_schedule', wagtail.fields.RichTextField(blank=True, help_text='Ej: Domingos 10am, Miércoles 7pm', verbose_name='Horarios de Culto')),
                ('map_embed_code', models.TextField(blank=True, help_text='Pegar el código <iframe> de Google Maps aquí', verbose_name='Código de Mapa (Embed)')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok')),
                ('delegated_editors', models.ManyToManyField(blank=True, help_text='Miembros a los que el Pastor ha dado permiso para editar esta página.', related_name='editable_iglesias', to=settings.AUTH_USER_MODEL, verbose_name='Editores Delegados')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Principal (Hero)')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo de la Iglesia')),
            ],
            options={
                'verbose_name': 'Iglesia',
                'verbose_name_plural': 'Iglesias',
            },
            bases=('wagtailcore.page',),
        ),
    ]
