# Generated by Django 5.2.1 on 2025-12-28 00:36

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0008_iglesiaeventpage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='iglesiapage',
            name='bank_information',
            field=wagtail.fields.RichTextField(blank=True, help_text='Cuentas bancarias e instrucciones para ofrendar.', verbose_name='Información Bancaria'),
        ),
        migrations.AddField(
            model_name='iglesiapage',
            name='donation_qr_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Código QR para Donaciones'),
        ),
    ]
