# Generated by Django 5.2.1 on 2025-12-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0009_iglesiapage_bank_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iglesiaeventpage',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('jovenes', 'Jóvenes')], default='general', max_length=20, verbose_name='Categoría'),
        ),
    ]
