# Generated by Django 5.2.9 on 2025-12-28 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0010_iglesiaeventpage_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('youtube_url', models.URLField(verbose_name='URL de YouTube')),
                ('is_live', models.BooleanField(default=False, verbose_name='En Vivo')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermons', to='iglesias.iglesiapage')),
            ],
            options={
                'verbose_name': 'Predicación',
                'verbose_name_plural': 'Predicaciones',
                'ordering': ['-date_added'],
            },
        ),
    ]
