# Generated by Django 5.2.9 on 2025-12-28 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0011_sermon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreachMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('category', models.CharField(choices=[('amor_de_dios', 'El Amor de Dios'), ('salvacion', 'La Salvación'), ('bautismo', 'El Bautismo'), ('espiritu_santo', 'El Espíritu Santo y sus dones'), ('otros', 'Otros')], default='otros', max_length=30, verbose_name='Categoría')),
                ('ppt_file', models.FileField(upload_to='preach_materials/ppts/', verbose_name='PPT')),
                ('extra_file', models.FileField(blank=True, null=True, upload_to='preach_materials/extra/', verbose_name='Archivo extra')),
                ('youtube_links', models.TextField(blank=True, help_text='One URL per line', verbose_name='Enlaces de YouTube')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preach_materials', to='iglesias.iglesiapage')),
            ],
            options={
                'verbose_name': 'Material de Predicación',
                'verbose_name_plural': 'Materiales de Predicación',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
