# Generated by Django 3.0.5 on 2020-06-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Ingresa tu correo', max_length=100)),
                ('full_name', models.CharField(help_text='Nombres y apellidos', max_length=100)),
            ],
        ),
    ]
