# Generated by Django 3.0.5 on 2020-06-04 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_auto_20200603_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Suscrito', 'verbose_name_plural': 'Suscritos'},
        ),
    ]
