# Generated by Django 5.2.1 on 2025-05-24 15:09

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctrinaAvanzadaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for the page')),
            ],
            options={
                'verbose_name': 'Doctrina Avanzada',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DoctrinaBasicaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for the page')),
            ],
            options={
                'verbose_name': 'Doctrina Basica',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DoctrinaIntermediaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for the page')),
            ],
            options={
                'verbose_name': 'Doctrina Intermedia',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DoctrinaEntryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(auto_now_add=True, help_text='Date the entry was created', verbose_name='Post date')),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Main content of the entry')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='Date the entry was last modified')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='User who last modified this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctrina_entries_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctrina Entry',
            },
            bases=('wagtailcore.page',),
        ),
    ]
