# Generated by Django 3.0.5 on 2020-09-21 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctrina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctrinapage',
            name='link_page_doctrina_basica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='doctrina.DoctrinaLevelPage'),
        ),
    ]
