# Generated by Django 5.2.1 on 2025-05-24 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrina', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctrinaentrypage',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctrina_entries_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
