# Generated by Django 5.2.1 on 2025-05-24 15:54

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrina', '0002_doctrinaentrypage_created_by'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctrinaentrypage',
            name='abstract',
            field=wagtail.fields.RichTextField(blank=True, help_text='A brief summary of the entry (optional)'),
        ),
        migrations.AddField(
            model_name='doctrinaentrypage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Optional image to accompany the entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='doctrinaentrypage',
            name='references',
            field=wagtail.fields.RichTextField(blank=True, help_text='Citations or references for the entry (optional)'),
        ),
        migrations.CreateModel(
            name='DoctrinaEntryPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='doctrina.doctrinaentrypage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='doctrinaentrypage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Tags to categorize the entry (e.g., theology, doctrine)', through='doctrina.DoctrinaEntryPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
