# Generated by Django 3.0.5 on 2020-06-05 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('doctrina', '0002_auto_20200604_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctrinapage',
            old_name='link_page',
            new_name='link_page_a',
        ),
        migrations.AddField(
            model_name='doctrinapage',
            name='link_page_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='doctrinapage',
            name='link_page_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
