# Generated by Django 5.2.1 on 2025-08-05 13:15

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrina', '0003_doctrinaentrypage_abstract_doctrinaentrypage_image_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctrinaHome',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(default='En la Iglesia de Cristo Ministerios Elim, la doctrina es el fundamento que guía nuestra fe y práctica, edificando al Cuerpo de Cristo para vivir en santidad y cumplir la Gran Comisión. Basados en la Biblia como la Palabra infalible de Dios, ofrecemos un proceso de formación doctrinal progresivo dividido en tres niveles: Doctrina Básica, Doctrina Intermedia y Doctrina Avanzada. Cada nivel está diseñado para equipar a los creyentes con un entendimiento profundo de las Escrituras, fortaleciendo su relación con Dios y preparándolos para el servicio en Su Reino.', help_text='Texto introductorio para la página de doctrina')),
            ],
            options={
                'verbose_name': 'Doctrina Home',
            },
            bases=('wagtailcore.page',),
        ),
    ]
