# Generated by Django 3.0.5 on 2020-06-05 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctrina', '0003_auto_20200604_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctrinapage',
            old_name='link_page_a',
            new_name='link_page_doctrina_avanzada',
        ),
        migrations.RenameField(
            model_name='doctrinapage',
            old_name='link_page_b',
            new_name='link_page_doctrina_basica',
        ),
        migrations.RenameField(
            model_name='doctrinapage',
            old_name='link_page_c',
            new_name='link_page_doctrina_intermedia',
        ),
    ]
