# Generated by Django 5.2.1 on 2025-08-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctrina', '0004_doctrinahome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctrinaHome',
        ),
    ]
