# Generated by Django 4.2.7 on 2023-12-02 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('doctrina', '0004_doctrinalevelpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctrinapagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
    ]
