# Generated by Django 5.2.1 on 2025-08-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrina', '0005_delete_doctrinahome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctrinaentrypage',
            name='date',
            field=models.DateField(blank=True, default=None, help_text='Date the entry was created', verbose_name='Post date'),
        ),
    ]
