# Generated by Django 3.0.5 on 2020-06-07 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('doctrina', '0005_auto_20200604_2132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctrinaListingTopicPage',
        ),
    ]
