# Generated by Django 3.0.5 on 2020-08-30 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('doctrina', '0006_delete_doctrinalistingtopicpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctrinalevelpage',
            name='level_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
