# Generated by Django 5.2.1 on 2025-08-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrina', '0006_alter_doctrinaentrypage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctrinaentrypage',
            name='date',
            field=models.DateField(blank=True, default=None, help_text='Date the entry was created', null=True, verbose_name='Post date'),
        ),
    ]
