# Generated by Django 5.2.9 on 2025-12-28 02:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrina', '0007_alter_doctrinaentrypage_date'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctrinaIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for the page')),
            ],
            options={
                'verbose_name': 'Doctrina Index',
            },
            bases=('wagtailcore.page',),
        ),
    ]
