# Generated by Django 5.2.9 on 2025-12-28 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrina', '0008_doctrinaindexpage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctrinaavanzadapage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Header image for the category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='doctrinabasicapage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Header image for the category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='doctrinaindexpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Header image for the category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='doctrinaintermediapage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Header image for the category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
