# Generated by Django 5.2.9 on 2025-12-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrina', '0009_doctrinaavanzadapage_image_doctrinabasicapage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctrinaentrypage',
            name='apostle_last_edit_date',
            field=models.DateTimeField(blank=True, help_text='Date when the Apostle last edited this entry', null=True),
        ),
    ]
