# Generated by Django 5.2.9 on 2025-12-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrina', '0010_doctrinaentrypage_apostle_last_edit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctrinaentrypage',
            name='date',
            field=models.DateField(blank=True, help_text='Fecha de creación de la entrada', null=True, verbose_name='Fecha de Publicación'),
        ),
    ]
