# Generated by Django 5.2.9 on 2025-12-28 05:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrina', '0011_alter_doctrinaentrypage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctrinaentrypage',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Fecha de creación de la entrada', null=True, verbose_name='Fecha de Publicación'),
        ),
    ]
