# Generated by Django 5.2.9 on 2025-12-30 23:33

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrina', '0012_alter_doctrinaentrypage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctrinaentrypage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtítulo opcional para la lección', max_length=255, null=True, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='doctrinaentrypage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, help_text='Contenido principal de la lección', verbose_name='Contenido'),
        ),
        migrations.CreateModel(
            name='DoctrinaYouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('url', models.URLField(help_text='Enlace completo del video de YouTube (ej: https://www.youtube.com/watch?v=...)', verbose_name='URL de YouTube')),
                ('title', models.CharField(blank=True, help_text='Título descriptivo del video (opcional)', max_length=255, null=True, verbose_name='Título del video')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_videos', to='doctrina.doctrinaentrypage')),
            ],
            options={
                'verbose_name': 'Video de YouTube',
                'verbose_name_plural': 'Videos de YouTube',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
