# Generated by Django 5.2.9 on 2026-01-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrina', '0013_doctrinaentrypage_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctrinaentrypage',
            name='image_display_style',
            field=models.CharField(choices=[('hero', 'Banner Hero (Ancho completo arriba)'), ('wrapped', 'Rodeada de Texto (Dentro del contenido)')], default='hero', help_text='Selecciona cómo quieres que se muestre la imagen principal', max_length=20, verbose_name='Estilo de visualización de imagen'),
        ),
        migrations.AlterField(
            model_name='doctrinayoutubevideo',
            name='title',
            field=models.CharField(blank=True, help_text='Título descriptivo del video (se obtiene automáticamente si lo dejas vacío)', max_length=255, null=True, verbose_name='Título del video'),
        ),
    ]
